#!/usr/bin/env bash

# Use brillo to logarithmically adjust laptop screen brightness
# and send a notification displaying the current brightness level after.

send_notification() {
	brightness=$(printf "%.0f\n" "$(brillo -G)")
	notify-send -a "changebrightness" -u low -r 9991 -h int:value:"$brightness" -i "brightness-$1" -t 2000 "Brightness: $brightness%"
}

case $1 in
up)
	pkexec brillo -A 5
	send_notification "$1"
	;;
down)
	pkexec brillo -U 5
	send_notification "$1"
	;;
esac
